import { castArray, isNil, pipe, every } from 'lodash/fp';
import { differenceInHours, parseISO } from 'date-fns';
import { getService } from '../utils/getService.js';
import { API_TOKEN_TYPE } from '../utils/constants.js';
import { errors } from '@strapi/utils';

const { UnauthorizedError, ForbiddenError } = errors;

export default ({ strapi }) => {
	const apiTokenService = getService({ type: 'admin', plugin: 'api-token' });
	const jwtService = getService({ name: 'jwt', plugin: 'users-permissions' });
	const userService = getService({ name: 'user', plugin: 'users-permissions' });

	/**
	 * Admin Session Strategy - for Strapi Admin Panel users
	 * Uses session tokens generated by presence controller
	 */
	const admin = {
		name: 'io-admin',
		credentials: function (user) {
			return `${this.name}-${user.id}`;
		},
		authenticate: async function (auth) {
			const token = auth.token;

			if (!token) {
				throw new UnauthorizedError('Invalid admin credentials');
			}

			try {
				const presenceController = strapi.plugin('io').controller('presence');
				const session = presenceController.consumeSessionToken(token);

				if (!session) {
					throw new UnauthorizedError('Invalid or expired session token');
				}

				return session.user;
			} catch (error) {
				strapi.log.warn('[plugin-io] Admin session verification failed:', error.message);
				throw new UnauthorizedError('Invalid admin credentials');
			}
		},
		getRoomName: function (user) {
			return `${this.name}-user-${user.id}`;
		},
	};

	const role = {
		name: 'io-role',
		credentials: function (role) {
			return `${this.name}-${role.id}`;
		},
		authenticate: async function (auth) {
			const token = await jwtService.verify(auth.token);

			if (!token) {
				throw new UnauthorizedError('Invalid credentials');
			}

			const { id } = token;

			if (id === undefined) {
				throw new UnauthorizedError('Invalid credentials');
			}

			const user = await userService.fetchAuthenticatedUser(id);

			if (!user) {
				throw new UnauthorizedError('Invalid credentials');
			}

			const advancedSettings = await strapi
				.store({ type: 'plugin', name: 'users-permissions' })
				.get({ key: 'advanced' });

			if (advancedSettings.email_confirmation && !user.confirmed) {
				throw new UnauthorizedError('Invalid credentials');
			}

			if (user.blocked) {
				throw new UnauthorizedError('Invalid credentials');
			}

			const roles = await strapi.documents('plugin::users-permissions.role').findMany({
				filters: { id: user.role.id },
				fields: ['id', 'name'],
				limit: 1,
			});
			return roles.length > 0 ? roles[0] : null;
		},
		verify: function (auth, config) {
			const { ability } = auth;

			if (!ability) {
				throw new UnauthorizedError();
			}

			const isAllowed = pipe(
				castArray,
				every((scope) => ability.can(scope)),
			)(config.scope);

			if (!isAllowed) {
				throw new ForbiddenError();
			}
		},
		getRoomName: function (role) {
			return `${this.name}-${role.name.toLowerCase()}`;
		},
		getRooms: function () {
			return strapi.documents('plugin::users-permissions.role').findMany({
				fields: ['id', 'name'],
				populate: { permissions: true },
			});
		},
	};

	const token = {
		name: 'io-token',
		credentials: function (token) {
			return token;
		},
		authenticate: async function (auth) {
			const token = auth.token;

			if (!token) {
				throw new UnauthorizedError('Invalid credentials');
			}

			// [EXCEPTION] admin::api-token is a Strapi Core Admin entity
			// Official Strapi implementation uses strapi.db.query() for admin::api-token
			const apiToken = await strapi.db.query('admin::api-token').findOne({
				where: { accessKey: apiTokenService.hash(token) },
				select: ['id', 'name', 'type', 'lastUsedAt', 'expiresAt'],
				populate: ['permissions'],
			});

			if (!apiToken) {
				throw new UnauthorizedError('Invalid credentials');
			}

			const currentDate = new Date();
			if (!isNil(apiToken.expiresAt)) {
				const expirationDate = new Date(apiToken.expiresAt);
				if (expirationDate < currentDate) {
					throw new UnauthorizedError('Token expired');
				}
			}

			// [EXCEPTION] Using Query Engine as per Strapi Core implementation
			if (!apiToken.lastUsedAt || differenceInHours(currentDate, parseISO(apiToken.lastUsedAt)) >= 1) {
				await strapi.db.query('admin::api-token').update({
					where: { id: apiToken.id },
					data: { lastUsedAt: currentDate },
				});
			}

			return apiToken;
		},
		verify: function (auth, config) {
			const { credentials: apiToken, ability } = auth;
			if (!apiToken) {
				throw new UnauthorizedError('Token not found');
			}

			if (!isNil(apiToken.expiresAt)) {
				const currentDate = new Date();
				const expirationDate = new Date(apiToken.expiresAt);
				if (expirationDate < currentDate) {
					throw new UnauthorizedError('Token expired');
				}
			}

			if (apiToken.type === API_TOKEN_TYPE.FULL_ACCESS) {
				return;
			} else if (apiToken.type === API_TOKEN_TYPE.READ_ONLY) {
				const scopes = castArray(config.scope);

				if (config.scope && scopes.every(isReadScope)) {
					return;
				}
			} else if (apiToken.type === API_TOKEN_TYPE.CUSTOM) {
				if (!ability) {
					throw new ForbiddenError();
				}

				const scopes = castArray(config.scope);

				const isAllowed = scopes.every((scope) => ability.can(scope));

				if (isAllowed) {
					return;
				}
			}

			throw new ForbiddenError();
		},
		getRoomName: function (token) {
			return `${this.name}-${token.name.toLowerCase()}`;
		},
		getRooms: function () {
			// [EXCEPTION] Using Query Engine as per Strapi Core implementation
			return strapi.db.query('admin::api-token').findMany({
				select: ['id', 'type', 'name'],
				where: {
					$or: [
						{
							expiresAt: {
								$gte: new Date(),
							},
						},
						{
							expiresAt: null,
						},
					],
				},
				populate: ['permissions'],
			});
		},
	};

	return {
		admin,
		role,
		token,
	};
};
