'use strict';

const { castArray, isNil, pipe, every } = require('lodash/fp');
const { differenceInHours, parseISO } = require('date-fns');
const { getService } = require('../utils/getService');
const { API_TOKEN_TYPE } = require('../utils/constants');
const { UnauthorizedError, ForbiddenError } = require('@strapi/utils').errors;

module.exports = ({ strapi }) => {
	const apiTokenService = getService({ type: 'admin', plugin: 'api-token' });
	const jwtService = getService({ name: 'jwt', plugin: 'users-permissions' });
	const userService = getService({ name: 'user', plugin: 'users-permissions' });

	/**
	 * Admin Session Strategy - for Strapi Admin Panel users
	 * Uses session tokens generated by presence controller
	 * Implements secure token validation with usage tracking
	 */
	const admin = {
		name: 'io-admin',
		credentials: function (user) {
			return `${this.name}-${user.id}`;
		},
		/**
		 * Authenticates admin user via session token
		 * @param {object} auth - Auth object containing token
		 * @param {object} socket - Socket instance for registration
		 * @returns {object} User data if authenticated
		 * @throws {UnauthorizedError} If authentication fails
		 */
		authenticate: async function (auth, socket) {
			const token = auth.token;

			if (!token || typeof token !== 'string') {
				strapi.log.warn('[plugin-io] Admin auth failed: No token provided');
				throw new UnauthorizedError('Invalid admin credentials');
			}

			// Basic token format validation (UUID format)
			const uuidRegex = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
			if (!uuidRegex.test(token)) {
				strapi.log.warn('[plugin-io] Admin auth failed: Invalid token format');
				throw new UnauthorizedError('Invalid token format');
			}

			try {
				// Get presence controller to validate session token
				const presenceController = strapi.plugin('io').controller('presence');
				const session = presenceController.consumeSessionToken(token);

				if (!session) {
					strapi.log.warn('[plugin-io] Admin auth failed: Token not valid or expired');
					throw new UnauthorizedError('Invalid or expired session token');
				}

				// Register socket with this token for tracking
				if (socket?.id) {
					presenceController.registerSocket(socket.id, token);
				}

				strapi.log.info(`[plugin-io] Admin authenticated: User ID ${session.userId}`);

				return {
					id: session.userId,
					...session.user,
				};
			} catch (error) {
				if (error instanceof UnauthorizedError) {
					throw error;
				}
				strapi.log.error('[plugin-io] Admin session verification error:', error.message);
				throw new UnauthorizedError('Authentication failed');
			}
		},
		/**
		 * Cleanup when socket disconnects
		 * @param {object} socket - Socket instance
		 */
		onDisconnect: function (socket) {
			if (socket?.id) {
				const presenceController = strapi.plugin('io').controller('presence');
				presenceController.unregisterSocket(socket.id);
			}
		},
		getRoomName: function (user) {
			return `${this.name}-user-${user.id}`;
		},
		/**
		 * Admin users have full access - verify always passes
		 * @param {object} auth - Auth object
		 * @param {object} config - Config with scope
		 */
		verify: function (auth, config) {
			// Admin users have full access to everything
			// No verification needed
			return;
		},
		/**
		 * Returns active admin sessions for broadcast
		 * Admin users have full access, so we return them with full_access permissions
		 * @returns {Promise<Array>} Array of admin session objects with permissions
		 */
		getRooms: async function () {
			try {
				const presenceController = strapi.plugin('io').controller('presence');
				
				// Check if presence controller and getActiveSessions exist
				if (!presenceController?.getActiveSessions) {
					return [];
				}
				
				const activeSessions = presenceController.getActiveSessions();
				
				// Transform sessions to room objects with full_access permissions
				// Admin users have full access by nature
				return activeSessions.map((session) => ({
					id: session.userId,
					name: `admin-${session.userId}`,
					type: 'full-access', // Grants full access to all content types
					permissions: [], // Empty permissions array - full-access type bypasses permission check
					...session,
				}));
			} catch (error) {
				strapi.log.warn('[plugin-io] Admin getRooms error:', error.message);
				return [];
			}
		},
	};

	const role = {
		name: 'io-role',
		credentials: function (role) {
			return `${this.name}-${role.id}`;
		},
		authenticate: async function (auth) {
			// adapted from https://github.com/strapi/strapi/blob/main/packages/plugins/users-permissions/server/strategies/users-permissions.js#L12
			const token = await jwtService.verify(auth.token);

			if (!token) {
				throw new UnauthorizedError('Invalid credentials');
			}

			const { id } = token;

			// Invalid token
			if (id === undefined) {
				throw new UnauthorizedError('Invalid credentials');
			}

			const user = await userService.fetchAuthenticatedUser(id);

			// No user associated to the token
			if (!user) {
				throw new UnauthorizedError('Invalid credentials');
			}

			const advancedSettings = await strapi
				.store({ type: 'plugin', name: 'users-permissions' })
				.get({ key: 'advanced' });

			// User not confirmed
			if (advancedSettings.email_confirmation && !user.confirmed) {
				throw new UnauthorizedError('Invalid credentials');
			}

			// User blocked
			if (user.blocked) {
				throw new UnauthorizedError('Invalid credentials');
			}

			// Find role using Document Service API (Strapi v5)
			const roles = await strapi.documents('plugin::users-permissions.role').findMany({
				filters: { id: user.role.id },
				fields: ['id', 'name'],
				limit: 1,
			});
			return roles.length > 0 ? roles[0] : null;
		},
		verify: function (auth, config) {
			// adapted from https://github.com/strapi/strapi/blob/main/packages/plugins/users-permissions/server/strategies/users-permissions.js#L80
			const { ability } = auth;

			if (!ability) {
				throw new UnauthorizedError();
			}

			const isAllowed = pipe(
				castArray,
				every((scope) => ability.can(scope)),
			)(config.scope);

			if (!isAllowed) {
				throw new ForbiddenError();
			}
		},
		getRoomName: function (role) {
			return `${this.name}-${role.name.toLowerCase()}`;
		},
		getRooms: function () {
			// fetch all role types using Document Service API (Strapi v5)
			return strapi.documents('plugin::users-permissions.role').findMany({
				fields: ['id', 'name'],
				populate: { permissions: true },
			});
		},
	};

	const token = {
		name: 'io-token',
		credentials: function (token) {
			return token;
		},
		authenticate: async function (auth) {
			// adapted from https://github.com/strapi/strapi/blob/main/packages/core/admin/server/strategies/api-token.js#L30
			const token = auth.token;

			if (!token) {
				throw new UnauthorizedError('Invalid credentials');
			}

			// Note: admin::api-token uses strapi.db.query() as it's a core admin entity
			// that doesn't follow the Document Service pattern
			const apiToken = await strapi.db.query('admin::api-token').findOne({
				where: { accessKey: apiTokenService.hash(token) },
				select: ['id', 'name', 'type', 'lastUsedAt', 'expiresAt'],
				populate: ['permissions'],
			});

			// token not found
			if (!apiToken) {
				throw new UnauthorizedError('Invalid credentials');
			}

			const currentDate = new Date();
			if (!isNil(apiToken.expiresAt)) {
				const expirationDate = new Date(apiToken.expiresAt);
				// token has expired
				if (expirationDate < currentDate) {
					throw new UnauthorizedError('Token expired');
				}
			}

			// update lastUsedAt if the token has not been used in the last hour
			if (!apiToken.lastUsedAt || differenceInHours(currentDate, parseISO(apiToken.lastUsedAt)) >= 1) {
				await strapi.db.query('admin::api-token').update({
					where: { id: apiToken.id },
					data: { lastUsedAt: currentDate },
				});
			}

			return apiToken;
		},
		verify: function (auth, config) {
			// adapted from https://github.com/strapi/strapi/blob/main/packages/core/admin/server/strategies/api-token.js#L82
			const { credentials: apiToken, ability } = auth;
			if (!apiToken) {
				throw new UnauthorizedError('Token not found');
			}

			if (!isNil(apiToken.expiresAt)) {
				const currentDate = new Date();
				const expirationDate = new Date(apiToken.expiresAt);
				// token has expired
				if (expirationDate < currentDate) {
					throw new UnauthorizedError('Token expired');
				}
			}

			if (apiToken.type === API_TOKEN_TYPE.FULL_ACCESS) {
				return;
			} else if (apiToken.type === API_TOKEN_TYPE.READ_ONLY) {
				const scopes = castArray(config.scope);

				if (config.scope && scopes.every(isReadScope)) {
					return;
				}
			} else if (apiToken.type === API_TOKEN_TYPE.CUSTOM) {
				if (!ability) {
					throw new ForbiddenError();
				}

				const scopes = castArray(config.scope);

				const isAllowed = scopes.every((scope) => ability.can(scope));

				if (isAllowed) {
					return;
				}
			}

			throw new ForbiddenError();
		},
		getRoomName: function (token) {
			return `${this.name}-${token.name.toLowerCase()}`;
		},
		getRooms: function () {
			// fetch active token types
			// Note: admin::api-token uses strapi.db.query() as it's a core admin entity
			return strapi.db.query('admin::api-token').findMany({
				select: ['id', 'type', 'name'],
				where: {
					$or: [
						{
							expiresAt: {
								$gte: new Date(),
							},
						},
						{
							expiresAt: null,
						},
					],
				},
				populate: ['permissions'],
			});
		},
	};

	return {
		admin,
		role,
		token,
	};
};
